export {default as Bird1} from "./bird1.gif"
export {default as Bird2} from "./bird2.gif"
export {default as Car} from "./Car.png"    
export {default as Cloud1} from "./Cloud1.png"
export {default as Cloud2} from "./Cloud2.png"
export {default as Road} from "./Road.png"